// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title Groth16Verifier
/// @notice Verifies Groth16 ZK-SNARK proofs on FlowEVM using BN256 precompiles.
///         Used by FlowShield to verify compliance proofs without exposing identity data.
/// @dev Uses precompiles: ecAdd (0x06), ecMul (0x07), ecPairing (0x08)
contract Groth16Verifier {

    // ── Verification Key (set during deployment) ──
    // These points define the circuit's verification key from the trusted setup.
    // For production: generated by snarkjs during the ceremony.
    // For hackathon: using a demo circuit that proves "I know a secret s such that hash(s) = H"

    struct VerifyingKey {
        uint256[2] alpha1;      // G1 point
        uint256[2][2] beta2;    // G2 point
        uint256[2][2] gamma2;   // G2 point
        uint256[2][2] delta2;   // G2 point
        uint256[2][] ic;        // Input commitments (G1 points)
    }

    struct Proof {
        uint256[2] a;           // G1 point (pi_a)
        uint256[2][2] b;       // G2 point (pi_b)
        uint256[2] c;           // G1 point (pi_c)
    }

    // ── State ──
    VerifyingKey private vk;
    address public admin;
    uint256 public totalVerifications;

    // ── Events ──
    event ProofVerified(address indexed user, bytes32 proofHash, uint256 timestamp);
    event ProofRejected(address indexed user, string reason);
    event VerifyingKeyUpdated(uint256 icLength);

    modifier onlyAdmin() {
        require(msg.sender == admin, "Not admin");
        _;
    }

    constructor() {
        admin = msg.sender;
        _setDemoVerifyingKey();
    }

    /// @notice Verify a Groth16 proof against public inputs
    /// @param proof The proof points (pi_a, pi_b, pi_c)
    /// @param publicInputs The public signals from the circuit
    /// @return valid Whether the proof is valid
    function verifyProof(
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC,
        uint256[] calldata publicInputs
    ) external returns (bool valid) {
        require(publicInputs.length + 1 == vk.ic.length, "Invalid public inputs length");

        // Step 1: Compute the linear combination of public inputs
        // vk_x = ic[0] + sum(publicInputs[i] * ic[i+1])
        uint256[2] memory vkX = vk.ic[0];

        for (uint256 i = 0; i < publicInputs.length; i++) {
            require(publicInputs[i] < _snarkScalarField(), "Input too large");
            uint256[2] memory mulResult = _ecMul(vk.ic[i + 1], publicInputs[i]);
            vkX = _ecAdd(vkX, mulResult);
        }

        // Step 2: Verify the pairing equation
        // e(pi_a, pi_b) == e(alpha1, beta2) * e(vk_x, gamma2) * e(pi_c, delta2)
        //
        // Rearranged for single pairing check:
        // e(-pi_a, pi_b) * e(alpha1, beta2) * e(vk_x, gamma2) * e(pi_c, delta2) == 1
        valid = _pairingCheck(
            _negate(proofA),
            proofB,
            vk.alpha1,
            vk.beta2,
            vkX,
            vk.gamma2,
            proofC,
            vk.delta2
        );

        if (valid) {
            totalVerifications++;
            bytes32 proofHash = keccak256(abi.encodePacked(proofA, proofB, proofC));
            emit ProofVerified(msg.sender, proofHash, block.timestamp);
        } else {
            emit ProofRejected(msg.sender, "Pairing check failed");
        }

        return valid;
    }

    /// @notice Update the verifying key (admin only)
    /// @dev Used when the ZK circuit is updated or for testing
    function setVerifyingKey(
        uint256[2] calldata alpha1,
        uint256[2][2] calldata beta2,
        uint256[2][2] calldata gamma2,
        uint256[2][2] calldata delta2,
        uint256[2][] calldata ic
    ) external onlyAdmin {
        require(ic.length >= 2, "Need at least 2 IC points");

        vk.alpha1 = alpha1;
        vk.beta2 = beta2;
        vk.gamma2 = gamma2;
        vk.delta2 = delta2;

        delete vk.ic;
        for (uint256 i = 0; i < ic.length; i++) {
            vk.ic.push(ic[i]);
        }

        emit VerifyingKeyUpdated(ic.length);
    }

    /// @notice Transfer admin role
    function transferAdmin(address newAdmin) external onlyAdmin {
        require(newAdmin != address(0), "Zero address");
        admin = newAdmin;
    }

    // ── BN256 Precompile Wrappers ──

    /// @dev BN256 scalar field order
    function _snarkScalarField() internal pure returns (uint256) {
        return 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    }

    /// @dev Negate a G1 point (flip y coordinate)
    function _negate(uint256[2] memory p) internal pure returns (uint256[2] memory) {
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p[0] == 0 && p[1] == 0) {
            return p;
        }
        return [p[0], q - (p[1] % q)];
    }

    /// @dev ecAdd precompile (0x06) — adds two G1 points
    function _ecAdd(uint256[2] memory p1, uint256[2] memory p2) internal view returns (uint256[2] memory r) {
        uint256[4] memory input;
        input[0] = p1[0];
        input[1] = p1[1];
        input[2] = p2[0];
        input[3] = p2[1];

        assembly {
            if iszero(staticcall(sub(gas(), 2000), 0x06, input, 0x80, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev ecMul precompile (0x07) — scalar multiplication of G1 point
    function _ecMul(uint256[2] memory p, uint256 s) internal view returns (uint256[2] memory r) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;

        assembly {
            if iszero(staticcall(sub(gas(), 2000), 0x07, input, 0x60, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev ecPairing precompile (0x08) — BN256 pairing check (4 pairs)
    function _pairingCheck(
        uint256[2] memory a1, uint256[2][2] memory b1,
        uint256[2] memory a2, uint256[2][2] memory b2,
        uint256[2] memory a3, uint256[2][2] memory b3,
        uint256[2] memory a4, uint256[2][2] memory b4
    ) internal view returns (bool) {
        uint256[24] memory input;

        // Pair 1: e(-pi_a, pi_b)
        input[0]  = a1[0];  input[1]  = a1[1];
        input[2]  = b1[0][1]; input[3]  = b1[0][0];
        input[4]  = b1[1][1]; input[5]  = b1[1][0];

        // Pair 2: e(alpha1, beta2)
        input[6]  = a2[0];  input[7]  = a2[1];
        input[8]  = b2[0][1]; input[9]  = b2[0][0];
        input[10] = b2[1][1]; input[11] = b2[1][0];

        // Pair 3: e(vk_x, gamma2)
        input[12] = a3[0];  input[13] = a3[1];
        input[14] = b3[0][1]; input[15] = b3[0][0];
        input[16] = b3[1][1]; input[17] = b3[1][0];

        // Pair 4: e(pi_c, delta2)
        input[18] = a4[0];  input[19] = a4[1];
        input[20] = b4[0][1]; input[21] = b4[0][0];
        input[22] = b4[1][1]; input[23] = b4[1][0];

        uint256[1] memory result;
        assembly {
            if iszero(staticcall(sub(gas(), 2000), 0x08, input, 0x300, result, 0x20)) {
                revert(0, 0)
            }
        }

        return result[0] == 1;
    }

    /// @dev Set a demo verifying key for hackathon testing
    ///      In production, this would come from a real snarkjs trusted setup
    function _setDemoVerifyingKey() internal {
        // Demo verification key points (valid BN256 curve points)
        // These are placeholder values for the hackathon demo circuit
        // Real values would be generated by: snarkjs groth16 setup circuit.r1cs pot_final.ptau vk.json
        vk.alpha1 = [
            uint256(20491192805390485299153009773594534940189261866228447918068658471970481763042),
            uint256(9383485363053290200918347156157836566562967994039712273449902621266178545958)
        ];

        vk.beta2 = [
            [uint256(4252822878758300859123897981450591353533073413197771768651442665752259397132),
             uint256(6375614351688725206403948262868962793625744043794305715222011528459656738731)],
            [uint256(21847035105528745403288232691147584728191162732299865338377159692350059136679),
             uint256(10505242626370262277552901082094356697409835680220590971873171140371331206856)]
        ];

        vk.gamma2 = [
            [uint256(11559732032986387107991004021392285783925812861821192530917403151452391805634),
             uint256(10857046999023057135944570762232829481370756359578518086990519993285655852781)],
            [uint256(4082367875863433681332203403145435568316851327593401208105741076214120093531),
             uint256(8495653923123431417604973247489272438418190587263600148770280649306958101930)]
        ];

        vk.delta2 = [
            [uint256(11559732032986387107991004021392285783925812861821192530917403151452391805634),
             uint256(10857046999023057135944570762232829481370756359578518086990519993285655852781)],
            [uint256(4082367875863433681332203403145435568316851327593401208105741076214120093531),
             uint256(8495653923123431417604973247489272438418190587263600148770280649306958101930)]
        ];

        // IC points: ic[0] is the base, ic[1..n] correspond to public inputs
        // For our compliance circuit: 1 public input (compliance hash)
        vk.ic.push([
            uint256(18936818173480011669507163011118288089471243894022003995543532463720649243817),
            uint256(18556147586753789634670778212244811446448229326945855846642767021074501673839)
        ]);
        vk.ic.push([
            uint256(13255007916834727652488224264507980734667002316506525986986498653471930814639),
            uint256(9700284937755839886587817653858618966039933458458949861901949325978551338779)
        ]);
    }
}
